=== TavoloPerUno/FOC/XML Schema/Translation-List.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Translation-List">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Translation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:byte"/>
							<xs:element name="Language" type="xs:string"/>
							<xs:element name="Value" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== TavoloPerUno/FOC/XML/Translation-List.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by Marco Skulschus (Comelio GmbH) -->
<Translation-List xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XML%20Schema/Translation-List.xsd">
	<Translation>
		<ID>1</ID>
		<Language>de</Language>
		<Value>Kurskatalog</Value>
	</Translation>
	<Translation>
		<ID>1</ID>
		<Language>en</Language>
		<Value>Course Catalog</Value>
	</Translation>
	<Translation>
		<ID>2</ID>
		<Language>de</Language>
		<Value>Kursnr.</Value>
	</Translation>
	<Translation>
		<ID>2</ID>
		<Language>en</Language>
		<Value>Course ID</Value>
	</Translation>
	<Translation>
		<ID>3</ID>
		<Language>de</Language>
		<Value>Zielgruppe</Value>
	</Translation>
	<Translation>
		<ID>3</ID>
		<Language>en</Language>
		<Value>Target Group</Value>
	</Translation>
	<Translation>
		<ID>4</ID>
		<Language>de</Language>
		<Value>Methode</Value>
	</Translation>
	<Translation>
		<ID>4</ID>
		<Language>en</Language>
		<Value>Method</Value>
	</Translation>
	<Translation>
		<ID>5</ID>
		<Language>de</Language>
		<Value>Hersteller</Value>
	</Translation>
	<Translation>
		<ID>5</ID>
		<Language>en</Language>
		<Value>Manufacturer</Value>
	</Translation>
	<Translation>
		<ID>6</ID>
		<Language>de</Language>
		<Value>Niveau</Value>
	</Translation>
	<Translation>
		<ID>6</ID>
		<Language>en</Language>
		<Value>Level</Value>
	</Translation>
	<Translation>
		<ID>7</ID>
		<Language>de</Language>
		<Value>Termine</Value>
	</Translation>
	<Translation>
		<ID>7</ID>
		<Language>en</Language>
		<Value>Dates</Value>
	</Translation>
	<Translation>
		<ID>8</ID>
		<Language>de</Language>
		<Value>Lieferart</Value>
	</Translation>
	<Translation>
		<ID>8</ID>
		<Language>en</Language>
		<Value>Delivery mode</Value>
	</Translation>
	<Translation>
		<ID>9</ID>
		<Language>de</Language>
		<Value>Vorkenntnisse</Value>
	</Translation>
	<Translation>
		<ID>9</ID>
		<Language>en</Language>
		<Value>Prerequisites</Value>
	</Translation>
	<Translation>
		<ID>10</ID>
		<Language>de</Language>
		<Value>Methode</Value>
	</Translation>
	<Translation>
		<ID>10</ID>
		<Language>en</Language>
		<Value>Method</Value>
	</Translation>
	<Translation>
		<ID>11</ID>
		<Language>de</Language>
		<Value>Kurslevel</Value>
	</Translation>
	<Translation>
		<ID>11</ID>
		<Language>en</Language>
		<Value>Course level</Value>
	</Translation>
	<Translation>
		<ID>12</ID>
		<Language>de</Language>
		<Value>Dauer</Value>
	</Translation>
	<Translation>
		<ID>12</ID>
		<Language>en</Language>
		<Value>Duration</Value>
	</Translation>
	<Translation>
		<ID>13</ID>
		<Language>de</Language>
		<Value>Sprache</Value>
	</Translation>
	<Translation>
		<ID>13</ID>
		<Language>en</Language>
		<Value>Language</Value>
	</Translation>
	<Translation>
		<ID>14</ID>
		<Language>de</Language>
		<Value>file:///C:/Users/Manoradhan%20M/Desktop/Projects/Catalogs/Catalogs/StyleCatalogs/25%20Aug/</Value>
	</Translation>
	<Translation>
		<ID>14</ID>
		<Language>en</Language>
		<Value>file:///C:/Users/Manoradhan%20M/Desktop/Projects/Catalogs/Catalogs/StyleCatalogs/25%20Aug/</Value>
	</Translation>
	
	
	
</Translation-List>
